name: cached_s5_audio_exmaple
description: "An example project to show how to use cached_s5_audio."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cached_s5_audio:
    path: ../
  s5: ^0.2.0
  hive: ^2.2.3
  logger: ^2.4.0
  cached_s5_manager: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
