name: cached_s5_audio
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  cached_s5_manager: ^1.1.0
  flutter:
    sdk: flutter
  s5: ^0.2.0
  logger: ^2.4.0
  flutter_audio_waveforms: ^1.2.1+8
  audioplayers: ^6.0.0
  universal_io: ^2.2.2
  wave: ^0.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
